- name: import app set up from common role
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yml

- name: disable nginx
  ansible.builtin.command: dnf module disable nginx -y

- name: enable nginx
  ansible.builtin.command: dnf module enable nginx:1.24 -y

- name: install nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: remove html directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: create html directory 
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: directory

- name: copy nginx conf 
  ansible.builtin.template:
    src: nginx.conf.j2 #ansible opens templates and replaces
    dest: /etc/nginx/nginx.conf
  notify: restart nginx



