- name: install maven
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop:
  - maven
  - mysql

- name: download dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: move jar file
  ansible.builtin.command: mv target/{{ component }}-{{ version }}.0.jar {{ component }}.jar 
  args:
    chdir: /app

